#!/bin/bash
# CS 218
# Assignment #11 test script.
#
# ----------
# Initial checks.
#	Ensure executable file exists.
#
if [ -z $1 ]; then
	echo "Error, must provide executable file name."
	exit
fi
#
if [ ! -e $1 ] || [ ! -x $1 ]; then
	echo "Error, unable to find $1 executable file."
	exit
fi
#
# ---------------------------------------------------------
# Define script variables and function
#
bolded=`tput bold`
normal=`tput sgr0`
#
pause() {
	if [ "$1" = "skip" ]; then
		echo
	else
		echo
		echo -n "Press return to continue"
		read
		echo "------------------------"
	fi
}
#
# ----------
# Begin error tests.
#
clear
echo
echo "${bolded}CS 218 - Assignment #11 Testing Script${normal}"
echo
echo
echo
echo
echo "Note, this utility assumes the program is working or very"
echo "      close to working.  Testing on an incomplete"
echo "      program will not be useful."
echo
echo "Note, You can type cntrl-C to terminate an in-process script."
echo
echo
echo
pause $2
clear
#
# -----
# Initial checks for usage message and argument counts
echo "-------------------------------"
echo "Initial checks for usage message and argument counts"
echo
#
echo
echo "${bolded}Test -> should show usage message${normal}"
echo "./"$1""
./$1
#
echo
echo
echo "${bolded}Test -> should show command line error message${normal}"
echo "./"$1" -none"
./$1 -none
#
echo
echo "${bolded}Test -> should show command line error message${normal}"
echo "./"$1" -w hello"
./$1 -w hello
#
echo
echo "${bolded}Test -> should show command line error message${normal}"
echo "./"$1" -w hello -ic -f file.txt extra"
./$1 -w hello -ic -f file.txt extra
#
pause $2
clear
#
# -----
# input file argument checks
#
echo "-------------------------------"
echo "Error Testing -> Specifier Checks"
echo
#
echo
echo "${bolded}Test -> should show word specifier error message${normal}"
echo "./"$1" -wr hello -ic -f a11f3.txt"
./$1 -wr hello -ic -f a11f3.txt
#
echo
echo "${bolded}Test -> should show word specifier error message${normal}"
echo "./"$1" w hello -ic -f a11f3.txt"
./$1 w hello -ic -f a11f3.txt
#
echo
echo "${bolded}Test -> should show case specifier error message${normal}"
echo "./"$1" -w hello -icc -f a11f3.txt"
./$1 -w hello -icc -f a11f3.txt
#
echo
echo "${bolded}Test -> should show case specifier error message${normal}"
echo "./"$1" -w hello mc -f a11f3.txt"
./$1 -w hello mc -f a11f3.txt
#
pause $2
clear
#
echo "-------------------------------"
echo "Error Testing -> Specifier Checks (continued)"
echo
#
echo
echo "${bolded}Test -> should show specifier error message${normal}"
echo "./"$1" -w hello -mc f a11f3.txt"
./$1 -w hello -mc f a11f3.txt
#
echo
echo "${bolded}Test -> should show specifier error message${normal}"
echo "./"$1" -w hello -mc - a11f3.txt"
./$1 -w hello -mc - a11f3.txt
#
echo
echo "${bolded}Test -> should show specifier error message${normal}"
echo "./"$1" -w hello -mc -ff a11f3.txt"
./$1 -w hello -mc -ff a11f3.txt
#
pause $2
clear
#
echo "-------------------------------"
echo "Error Testing: -> Input file name checks"
echo
#
echo
echo "${bolded}Test -> should show input file open error message${normal}"
echo "./"$1" -w hello -mc -f FilesDoesNotExist.txt"
./$1 -w hello -mc -f FilesDoesNotExist.txt
#
echo
echo "${bolded}Test -> should show input file open error message${normal}"
echo "./"$1" -w hello -mc -f nul/l.txt"
./$1 -w hello -mc -f nul/l.txt
#
echo "testing" > accessTest.txt
chmod -rw accessTest.txt
#
#echo
#echo "${bolded}Test -> should show input file open error message${normal}"
#echo "./"$1" -w hello -mc -f accessTest.txt"
#./$1 -w hello -mc -f accessTest.txt
#
chmod +rw accessTest.txt
rm accessTest.txt
#
pause $2
clear
#
# ----------
# Begin execution tests.
#
echo "${bolded}Execution Tests...${normal}"
echo
#
# -----
echo
echo "${bolded}Test #1:${normal}"
echo "./"$1" -w the -ic -f a11f3.txt"
tst1=$(./$1 -w the -ic -f a11f3.txt)
echo $tst1
echo
#
if [ "$tst1" = "Found 'the' 3211 times." ]; then
	echo "Test #1 - Successful"
else
	echo "Test #1 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #2:${normal}"
echo "./"$1" -w the -mc -f a11f3.txt"
tst2=$(./$1 -w the -mc -f a11f3.txt)
echo $tst2
echo
#
if [ "$tst2" = "Found 'the' 3023 times." ]; then
	echo "Test #2 - Successful"
else
	echo "Test #2 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #3:${normal}"
echo "./"$1" -w Taxes -mc -f a11f3.txt"
tst3=$(./$1 -w Taxes -mc -f a11f3.txt)
echo $tst3
echo
#
if [ "$tst3" = "Found 'Taxes' 1 times." ]; then
	echo "Test #3 - Successful"
else
	echo "Test #3 - Fail"
fi
#
pause $2
clear
# -----
echo
echo
echo "${bolded}Test #4:${normal}"
echo "./"$1" -w taxes -ic -f a11f3.txt"
tst4=$(./$1 -w taxes -ic -f a11f3.txt)
echo $tst4
echo
#
if [ "$tst4" = "Found 'taxes' 2 times." ]; then
	echo "Test #4 - Successful"
else
	echo "Test #4 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #5:${normal}"
echo "./"$1" -w line -ic -f a11f4.txt"
tst5=$(./$1 -w line -ic -f a11f4.txt)
echo $tst5
echo
#
if [ "$tst5" = "Found 'line' 2450450 times." ]; then
	echo "Test #5 - Successful"
else
	echo "Test #5 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #6:${normal}"
echo "./"$1" -w line -mc -f a11f4.txt"
tst6=$(./$1 -w line -mc -f a11f4.txt)
echo $tst6
echo
#
if [ "$tst6" = "Found 'line' 0 times." ]; then
	echo "Test #6 - Successful"
else
	echo "Test #6 - Fail"
fi
#
pause $2
clear
# -----
echo
echo
echo "${bolded}Test #7:${normal}"
echo "./"$1" -w Shareware -ic -f a11f6.txt"
tst7=$(./$1 -w Shareware -ic -f a11f6.txt)
echo $tst7
echo
#
if [ "$tst7" = "Found 'Shareware' 5131 times." ]; then
	echo "Test #7 - Successful"
else
	echo "Test #7 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #8:${normal}"
echo "./"$1" -w Shareware -mc -f a11f6.txt"
tst8=$(./$1 -w Shareware -mc -f a11f6.txt)
echo $tst8
echo
#
if [ "$tst8" = "Found 'Shareware' 3522 times." ]; then
	echo "Test #8 - Successful"
else
	echo "Test #8 - Fail"
fi
#
# -----
echo
echo
echo "${bolded}Test #9:${normal}"
echo "./"$1" -w of -mc -f a11f6.txt"
tst9=$(./$1 -w of -mc -f a11f6.txt)
echo $tst9
echo
#
if [ "$tst9" = "Found 'of' 124443 times." ]; then
	echo "Test #9 - Successful"
else
	echo "Test #9 - Fail"
fi
#
pause $2
clear
# -----
echo
echo
echo "${bolded}Test #10:${normal}"
echo "./"$1" -w of -ic -f a11f6.txt"
tst10=$(./$1 -w of -ic -f a11f6.txt)
echo $tst10
echo
#
if [ "$tst10" = "Found 'of' 125225 times." ]; then
	echo "Test #10 - Successful"
else
	echo "Test #10 - Fail"
fi
#
echo
echo
echo "${bolded}Test #11:${normal}"
echo "./"$1" -w of -ic -f trivia.list"
tst11=$(./$1 -w of -ic -f trivia.list)
echo $tst11
echo
#
if [ "$tst11" = "Found 'of' 13055455 times." ]; then
	echo "Test #11 - Successful"
else
	echo "Test #11 - Fail"
fi
#
echo
echo
echo "${bolded}Test #12:${normal}"
echo "./"$1" -w of -mc -f trivia.list"
tst12=$(./$1 -w of -mc -f trivia.list)
echo $tst12
echo
#
if [ "$tst12" = "Found 'of' 13041311 times." ]; then
	echo "Test #12 - Successful"
else
	echo "Test #12 - Fail"
fi
#
#
# --------------------
# Done...
echo
echo

