all:
	g++ Day2A.cpp -o Day2A && ./Day2A && \
	g++ Day2B.cpp -o Day2B && ./Day2B && \
	g++ Day2C.cpp -o Day2C && ./Day2C && \
	g++ Day2D.cpp -o Day2D && ./Day2D

Day2A:
	g++ Day2A.cpp -o Day2A && ./Day2A

Day2B:
	g++ Day2B.cpp -o Day2B && ./Day2B

Day2C:
	g++ Day2C.cpp -o Day2C && ./Day2C

Day2D:
	g++ Day2D.cpp -o Day2D && ./Day2D

clean:
	rm -f Day2A Day2B Day2C Day2D